export const articleData = {
  kind: 'Listing',
  data: {
    modhash: '',
    dist: 2,
    children: [
      {
        kind: 't3',
        data: {
          approved_at_utc: null,
          subreddit: 'redditdev',
          selftext: "I take my heavily down (or up) voted material as submissions that people are most engaged with. I'd like to get all vote changes, the content that was changed and a link to it, in temporal order. Is this possible? Many thanks!",
          user_reports: [],
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title: "Are Votes' Timestamps Available by API",
          link_flair_richtext: [],
          subreddit_name_prefixed: 'r/redditdev',
          hidden: false,
          pwls: 6,
          link_flair_css_class: null,
          downs: 0,
          parent_whitelist_status: 'all_ads',
          hide_score: false,
          name: 't3_8q7wm5',
          quarantine: false,
          link_flair_text_color: 'dark',
          author_flair_background_color: null,
          subreddit_type: 'public',
          ups: 2,
          domain: 'self.redditdev',
          media_embed: {},
          author_flair_template_id: null,
          is_original_content: false,
          secure_media: null,
          is_reddit_media_domain: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: null,
          can_mod_post: false,
          score: 2,
          approved_by: null,
          thumbnail: '',
          edited: false,
          author_flair_css_class: null,
          author_flair_richtext: [],
          content_categories: null,
          is_self: true,
          mod_note: null,
          created: 1528734296.0,
          link_flair_type: 'text',
          wls: 6,
          post_categories: null,
          banned_by: null,
          author_flair_type: 'text',
          contest_mode: false,
          selftext_html: '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;I take my heavily down (or up) voted material as submissions that people are most engaged with. I&amp;#39;d like to get all vote changes, the content that was changed and a link to it, in temporal order. Is this possible? Many thanks!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: false,
          pinned: false,
          over_18: false,
          media: null,
          media_only: false,
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: null,
          rte_mode: 'markdown',
          visited: false,
          num_reports: null,
          distinguished: null,
          subreddit_id: 't5_2qizd',
          mod_reason_by: null,
          removal_reason: null,
          id: '8q7wm5',
          report_reasons: null,
          author: 'cruyff8',
          num_crossposts: 0,
          num_comments: 9,
          send_replies: true,
          author_flair_text_color: null,
          permalink: '/r/redditdev/comments/8q7wm5/are_votes_timestamps_available_by_api/',
          whitelist_status: 'all_ads',
          stickied: false,
          url: 'https://www.reddit.com/r/redditdev/comments/8q7wm5/are_votes_timestamps_available_by_api/',
          subreddit_subscribers: 14360,
          created_utc: 1528705496.0,
          mod_reports: [],
          is_video: false,
        },
      },
      {
        kind: 't3',
        data: {
          approved_at_utc: null,
          subreddit: 'redditdev',
          selftext: "I apologize if this is a noob question. I am building my first reddit bot and am looking for a more efficient way of analyzing user comments. I was looping through each top submission in the most popular subreddits, but this is costly. I would like a way to simply read comments as they come in, if possible.  \n\nWould something like this work? I have been doing a bit of searching. What exactly is happening with this code? I have seen it in a few places.\n\ncomments = praw.helpers.comment_stream(reddit, 'all', limit=None)\n   \n\n",
          user_reports: [],
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title: 'What is the best way to get all new comments on reddit?',
          link_flair_richtext: [
            {
              e: 'text',
              t: 'PRAW',
            },
          ],
          subreddit_name_prefixed: 'r/redditdev',
          hidden: false,
          pwls: 6,
          link_flair_css_class: '',
          downs: 0,
          parent_whitelist_status: 'all_ads',
          hide_score: false,
          name: 't3_8q6lcv',
          quarantine: false,
          link_flair_text_color: 'dark',
          author_flair_background_color: null,
          subreddit_type: 'public',
          ups: 1,
          domain: 'self.redditdev',
          media_embed: {},
          author_flair_template_id: null,
          is_original_content: false,
          secure_media: null,
          is_reddit_media_domain: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: 'PRAW',
          can_mod_post: false,
          score: 1,
          approved_by: null,
          thumbnail: '',
          edited: false,
          author_flair_css_class: null,
          author_flair_richtext: [],
          content_categories: null,
          is_self: true,
          mod_note: null,
          created: 1528718757.0,
          link_flair_type: 'richtext',
          wls: 6,
          post_categories: null,
          banned_by: null,
          author_flair_type: 'text',
          contest_mode: false,
          selftext_html: '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;I apologize if this is a noob question. I am building my first reddit bot and am looking for a more efficient way of analyzing user comments. I was looping through each top submission in the most popular subreddits, but this is costly. I would like a way to simply read comments as they come in, if possible.  &lt;/p&gt;\n\n&lt;p&gt;Would something like this work? I have been doing a bit of searching. What exactly is happening with this code? I have seen it in a few places.&lt;/p&gt;\n\n&lt;p&gt;comments = praw.helpers.comment_stream(reddit, &amp;#39;all&amp;#39;, limit=None)&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          view_count: null,
          archived: false,
          no_follow: true,
          is_crosspostable: false,
          pinned: false,
          over_18: false,
          media: null,
          media_only: false,
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: null,
          rte_mode: 'markdown',
          visited: false,
          num_reports: null,
          distinguished: null,
          subreddit_id: 't5_2qizd',
          mod_reason_by: null,
          removal_reason: null,
          link_flair_background_color: '',
          id: '8q6lcv',
          report_reasons: null,
          author: 'YuckyCorpse',
          num_crossposts: 0,
          num_comments: 8,
          send_replies: true,
          author_flair_text_color: null,
          permalink: '/r/redditdev/comments/8q6lcv/what_is_the_best_way_to_get_all_new_comments_on/',
          whitelist_status: 'all_ads',
          stickied: false,
          url: 'https://www.reddit.com/r/redditdev/comments/8q6lcv/what_is_the_best_way_to_get_all_new_comments_on/',
          subreddit_subscribers: 14360,
          created_utc: 1528689957.0,
          mod_reports: [],
          is_video: false,
        },
      },
    ],
    after: 't3_8q6lcv',
    before: null,
  },
};


export const currentRedditData = [
  {
    kind: 'Listing',
    data: {
      modhash: '',
      dist: 1,
      children: [
        {
          kind: 't3',
          data: {
            approved_at_utc: null,
            subreddit: 'redditdev',
            selftext: "I take my heavily down (or up) voted material as submissions that people are most engaged with. I'd like to get all vote changes, the content that was changed and a link to it, in temporal order. Is this possible? Many thanks!",
            user_reports: [],
            saved: false,
            mod_reason_title: null,
            gilded: 0,
            clicked: false,
            title: "Are Votes' Timestamps Available by API",
            link_flair_richtext: [],
            subreddit_name_prefixed: 'r/redditdev',
            hidden: false,
            pwls: 6,
            link_flair_css_class: null,
            downs: 0,
            parent_whitelist_status: 'all_ads',
            hide_score: false,
            name: 't3_8q7wm5',
            quarantine: false,
            link_flair_text_color: 'dark',
            upvote_ratio: 0.67,
            author_flair_background_color: null,
            subreddit_type: 'public',
            ups: 2,
            domain: 'self.redditdev',
            media_embed: {},
            author_flair_template_id: null,
            is_original_content: false,
            secure_media: null,
            is_reddit_media_domain: false,
            category: null,
            secure_media_embed: {},
            link_flair_text: null,
            can_mod_post: false,
            score: 2,
            approved_by: null,
            thumbnail: '',
            edited: false,
            author_flair_css_class: null,
            author_flair_richtext: [],
            content_categories: null,
            is_self: true,
            mod_note: null,
            created: 1528734296.0,
            link_flair_type: 'text',
            wls: 6,
            post_categories: null,
            banned_by: null,
            author_flair_type: 'text',
            contest_mode: false,
            selftext_html: '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;I take my heavily down (or up) voted material as submissions that people are most engaged with. I&amp;#39;d like to get all vote changes, the content that was changed and a link to it, in temporal order. Is this possible? Many thanks!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
            likes: null,
            suggested_sort: null,
            banned_at_utc: null,
            view_count: null,
            archived: false,
            no_follow: false,
            is_crosspostable: false,
            pinned: false,
            over_18: false,
            media_only: false,
            can_gild: false,
            spoiler: false,
            locked: false,
            author_flair_text: null,
            rte_mode: 'markdown',
            visited: false,
            num_reports: null,
            distinguished: null,
            subreddit_id: 't5_2qizd',
            mod_reason_by: null,
            removal_reason: null,
            id: '8q7wm5',
            report_reasons: null,
            author: 'cruyff8',
            num_crossposts: 0,
            num_comments: 9,
            send_replies: true,
            mod_reports: [],
            author_flair_text_color: null,
            permalink: '/r/redditdev/comments/8q7wm5/are_votes_timestamps_available_by_api/',
            whitelist_status: 'all_ads',
            stickied: false,
            url: 'https://www.reddit.com/r/redditdev/comments/8q7wm5/are_votes_timestamps_available_by_api/',
            subreddit_subscribers: 14360,
            created_utc: 1528705496.0,
            media: null,
            is_video: false,
          },
        },
      ],
      after: null,
      before: null,
    },
  },
  {
    kind: 'Listing',
    data: {
      modhash: '',
      dist: null,
      children: [
        {
          kind: 't1',
          data: {
            subreddit_id: 't5_2qizd',
            approved_at_utc: null,
            ups: 4,
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_8q7wm5',
            author_flair_template_id: null,
            likes: null,
            no_follow: false,
            replies: {
              kind: 'Listing',
              data: {
                modhash: '',
                dist: null,
                children: [
                  {
                    kind: 'more',
                    data: {
                      count: 4,
                      name: 't1_e0hnu5v',
                      id: 'e0hnu5v',
                      parent_id: 't1_e0hanlo',
                      depth: 1,
                      children: [
                        'e0hnu5v',
                      ],
                    },
                  },
                ],
                after: null,
                before: null,
              },
            },
            user_reports: [],
            saved: false,
            id: 'e0hanlo',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            report_reasons: null,
            author: 'GeronimoHero',
            can_mod_post: false,
            send_replies: true,
            parent_id: 't3_8q7wm5',
            score: 4,
            approved_by: null,
            downs: 0,
            body: 'Nope, they are not. You couldn\u2019t do this anyway because of Reddit and their vote fuzzing. ',
            edited: false,
            author_flair_css_class: null,
            collapsed: false,
            author_flair_richtext: [],
            is_submitter: false,
            collapsed_reason: null,
            body_html: '&lt;div class="md"&gt;&lt;p&gt;Nope, they are not. You couldn\u2019t do this anyway because of Reddit and their vote fuzzing. &lt;/p&gt;\n&lt;/div&gt;',
            stickied: false,
            subreddit_type: 'public',
            can_gild: true,
            subreddit: 'redditdev',
            author_flair_text_color: null,
            score_hidden: false,
            permalink: '/r/redditdev/comments/8q7wm5/are_votes_timestamps_available_by_api/e0hanlo/',
            num_reports: null,
            name: 't1_e0hanlo',
            created: 1528746282.0,
            author_flair_text: null,
            rte_mode: 'markdown',
            created_utc: 1528717482.0,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            depth: 0,
            author_flair_background_color: null,
            mod_reports: [],
            mod_note: null,
            distinguished: null,
          },
        },
      ],
      after: null,
      before: null,
    },
  },
];

export const mockComments = [
  {
    data: {
      body: 'TEST',
      author: 'Me@me.com',
      created: 1528825256,
      postId: '8q7wm5',
    },
    id: 1,
  },
  {
    data: {
      body: 'HELO@',
      author: 'HELLO@ME.COM',
      created: 1528825277,
      postId: '8q4pwq',
    },
    id: 2,
  },
];
