export const FETCH_MOCK_COMMENTS = 'FETCH_MOCK_COMMENTS';
export const FETCH_REDDIT_ARTICLES = 'FETCH_REDDIT_ARTICLES';
export const FETCH_REDDIT_COMMENTS = 'FETCH_REDDIT_COMMENTS';
export const SET_PAGINATION_DATA = 'SET_PAGINATION_DATA';
export const FETCH_CURRENT_ARTICLE = 'FETCH_CURRENT_ARTICLE';
